source 'https://rubygems.org'

ruby ENV['CUSTOM_RUBY_VERSION'] || '2.2.4'
gem 'rails', '4.2.5'
gem 'pg'
gem 'actionmailer'
gem 'active_model_serializers'
gem 'http_accept_language'
gem 'globalize', '~> 5.0.0'
gem 'responders'
gem 'redis'
gem 'redis-namespace'
gem 'sidekiq', '~> 3.2.6'
gem 'kaminari'
gem 'carrierwave'
gem 'carrierwave-aws'
gem 'carrierwave_backgrounder'
gem 'high_voltage', '~> 2.2.1'
gem 'slim'
gem 'slim-rails'
gem 'uglifier', '>= 1.3.0'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'sass-rails', '>= 3.2'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jquery-easing-rails'
gem 'font-awesome-rails'
gem 'bourbon'
gem 'noty-rails'
gem 'simple_form'
gem 'mail_form'
gem 'country_select'
gem 'cocoon'
gem 'best_in_place', '~> 3.0.1'
gem 'redcarpet', '>= 3.0.0'
gem 'inplace_editing'
gem 'localizable_value'
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-instagram'
gem 'omniauth-twitter'
gem 'omniauth-linkedin'
gem 'omniauth-google-oauth2'
gem 'madmimi'
gem 'google-analytics-rails'
gem 'rollbar'
group :development do
  gem 'annotate', '>=2.6.0'
  gem 'pry-rails'
  gem 'quiet_assets'
  gem 'spring'
  gem 'xray-rails'
  gem 'rails-erd', github: 'paulwittmann/rails-erd', branch: 'mavericks'
  gem 'letter_opener'
end

group :test do
  gem 'shoulda-matchers'
end

group :development, :test do
  gem 'rspec-rails', '~> 3.0.0.beta'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :production do
  gem 'rails_12factor'
end
